url: http://www.lib13.com
baseurl: http://www.lib13.com/

# Site settings
title: Lib13
email: vaibhavb@lib13.com
description: "The mixing awesomeness."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fe5e36
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Vaibhav Bhandari
  pic: male-silhouette
  position: Mixologist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: github
      url: #

- name: Brian Hur
  pic: male-silhouette
  position: Director, Growth Hacking
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Srikumar R
  pic: male-silhouette
  position: Director, Computer Vision
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 113A 13th Ave E
  - line: Seattle, WA 98102

# Build settings
markdown: kramdown
permalink: pretty
